version: '3.8'

services:
    traccar:
      container_name: traccar
      image: traccar/traccar
      ports:
        - 5000-5150:5000-5150
        - 8082:8082
      depends_on:
        - mysql
      networks:
        - traccar-network
      volumes:
         - ./docker/traccar/conf:/opt/traccar/conf
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'traccar'
        MYSQL_USER: 'traccar'
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      # volumes:
      #   - ./docker/mysql/:/etc/mysql/
      networks:
        - traccar-network
    adminer:
      image: adminer
      ports:
        - 8080:8080
      networks:
        - traccar-network
networks:
  traccar-network: